### ISSUE TITLE
EmptyDataError and empty annotation file

### ISSUE THREAD

**Issue by pgonzale60** [FerriolCalvet/geneidBLASTx-nf#2]
Hi Ferriol,

I hope you're doing well. I've been trying to use the geneidx Nextflow pipeline that you developed, but I've run into a couple of issues that I wanted to bring to your attention.

1. I encountered an error when trying to predict genes in the genome assembly GCA_000002985.3 (_C. elegans_). The pipeline failed with the following error message: `pandas.errors.EmptyDataError: No columns to parse from file` at the "pyComputeIntrons" subworkflow.

2. I also noticed that when I tried to annotate only chromosome V, the pipeline completed successfully, but the annotation file was empty, even though we know there are thousands of genes in chromosome V.

I would really appreciate it if you could take a look into these issues and let me know if there's anything I can do to work around them or if there's a fix that you can implement.
Let me know if you need more information or data to help reproduce the problem.

Thanks in advance,
Pablo

**Comment by FerriolCalvet** [comment]
Hi Pablo,

Yes, it would be great if you could share more information on how you run Geneidx, which Nextflow version are you using and also some more information about the genome, in case it is different from the one in the ENA.

I have now tested it using the genome with the assembly name you provided as input and it worked well for me, but it would be great to know if you used a slightly different version of the genome or if you also modified some other parameters.

I downloaded the genome from [here](https://www.ebi.ac.uk/ena/browser/view/GCA_000002985.3) and run the following commands:
`export NXF_VER=22.04.4`
`nextflow run main.nf -with-docker --taxid 6239 --genome data/GCA_000002985.3.fa.gz`

Thank you very much for reporting the problems you have found, and if you can give me some more information I will test them and see how we can update the code.

Thank you!

Ferriol

**Comment by pgonzale60** [comment]
Hi Feriol,

Thank you so much for your help with this issue. Updating my Nextflow version as you suggested, did the trick. My previous version was [20.10.0].

Thank you for creating such a great tool and for being so dedicated (containerisation and pipelining) to making it better for the community.

Thank you again!
Pablo

**Comment by FerriolCalvet** [comment]
Thank you very much Pablo!
I am very happy to see that it is useful for you (and hopefully the community) and do not hesitate to contact me if you have any further questions or comments!

Thanks,

Ferriol
